### ISSUE TITLE
[REQUEST] 私は欲しいです mod fischl R18

### ISSUE THREAD

**Issue by Cesarrrcruz** [zeroruka/GI_Assets#129] opened 2022-08-02 22:56 UTC
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by zeroruka** [comment] 2022-08-07 13:49
Duplicate of #128

**Closed by zeroruka** 2022-08-07 13:49 UTC
Labels: request
