### ISSUE TITLE
[REQUEST]求一个胡桃

### ISSUE THREAD

**Issue by yogurt416** [zeroruka/GI_Assets#33] opened 2022-06-23 10:30 UTC
**Is your skin request related to a problem? Please describe.**

**Describe the style you'd like**
A clear and concise description of what you want it to look like.

**Additional context**
Add any other context or screenshots about the skin request here.

**Comment by zeroruka** [comment] 2022-06-23 10:37
Duplicate of #21

**Closed by zeroruka** 2022-06-23 10:37 UTC
Labels: duplicate, request
